
spring:
  datasource:
    url: jdbc:h2:file:~/jim-app
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none # disable for use Liquibase

liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.yaml
  contexts: dev

app:
  bigdecimalOperationsScale: 3
  operationWhenAddFormat: "yyyy-MM-dd HH:mm:ss"